export const VOICE = {
  emptyCart: "Votre panier est calme pour l'instant.",
  emptyWishlist: "Aucun coup de cœur enregistré.",
  outOfStock: "Bientôt de retour",
  lowStock: "Plus que quelques pièces",
  addToCartCta: "Ajouter au panier",
  buyNowCta: "Acheter",
  newsletterPitch: "Recevez nos sélections en avant-première et nos rituels saisonniers.",
  newsletterCta: "Je m'inscris",
  heroTagline: "Prenez soin de vous, avec douceur.",
  heroSubtitle: "Parapharmacie & matériel médical, sélectionné avec amour à Nabeul.",
  trustedBrandsLabel: "Marques de confiance",
  contactBaseline: "Une question ? Notre équipe est joignable du lundi au samedi.",
  emptyCartTitle: "Votre panier est calme pour l'instant.",
  emptyCartCta: "Découvrir la boutique",
  checkoutTitle: "Finaliser votre commande",
  codNotice: "Vous payez à la livraison, en main propre, en toute sérénité.",
  orderConfirmed: "Merci ! Votre commande est entre nos mains.",
  orderConfirmedSub:
    "Nous préparons votre colis avec soin. Un appel de confirmation suit dans la journée.",
  loginTitle: "Bon retour parmi nous.",
  signupTitle: "Créez votre compte Jasmin.",
  notreHistoireHero: "Le soin, comme un rituel.",
  filtersLabel: "Filtres",
  applyFiltersCta: "Appliquer",
  clearFiltersCta: "Tout effacer",
  addToWishlistCta: "Ajouter aux favoris",
  outOfStockBadge: "Bientôt de retour",
  inStockBadge: "En stock — livraison sous 48h",
  shippingFree: "Livraison gratuite",
  shippingFlat: "Livraison 7,000 TND",
  shippingFreeAbove: "Livraison gratuite dès 200,000 TND",
  dashboardWelcome: "Bonjour {name}, voici l'essentiel du jour.",
  emptyOrdersQueue: "Aucune commande en attente. Belle journée !",
  emptyLowStock: "Tous les rayons sont bien remplis.",
  inviteSent: "Invitation envoyée. Votre collègue recevra un lien magique.",
  refundConfirmed: "Remboursement enregistré, le stock est rétabli.",
  walkInOrderCreated: "Vente en magasin enregistrée.",
  productPublished: "Produit publié — visible sur la boutique.",
  productUnpublished: "Produit masqué — retiré de la boutique.",
  variantAdded: "Déclinaison ajoutée.",
  inventoryAdjusted: "Stock ajusté.",
  auditLogEmpty: "Aucun événement pour ces filtres.",
  posPaymentLabel: "Espèces",
  biTitle: "Décisionnel",
  biEmpty: "Pas encore d'activité sur cette période.",
  biPeriod7d: "7 jours",
  biPeriod30d: "30 jours",
  biPeriod90d: "90 jours",
  biPeriod12m: "12 mois",
  biPeriodAll: "Depuis le début",
  biBestSellers: "Meilleures ventes",
  biSalesTrend: "Tendances de vente",
  biBasket: "Paniers types",
  biStockHealth: "Santé du stock",
  biCohorts: "Cohortes clients",
  biFunnel: "Conversion",
  biSubtitleQty: "Par quantité",
  biSubtitleRevenue: "Par chiffre d'affaires",
  biReorderHint: "À réapprovisionner",
  biDeadStockHint: "Pas de vente sur la période",
  biRevenueLabel: "Chiffre d'affaires",
  biOrdersLabel: "Commandes",
  biAovLabel: "Panier moyen",
  biNewCustomersLabel: "Nouveaux clients",
  biRepeatRateLabel: "Taux de fidélité",
  biConversionRateLabel: "Taux de conversion",
  biLiftLabel: "Affinité",
  biSeenTogetherLabel: "Vu ensemble",
  biTurnoverLabel: "Rotation",
  biDaysOfCoverLabel: "Jours de stock",
} as const;

export type VoiceKey = keyof typeof VOICE;
